/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_Caff_Parser_Wrapper_WRAP_H_
#define SWIG_Caff_Parser_Wrapper_WRAP_H_

class SwigDirector_Parser : public Parser, public Swig::Director {

public:
    SwigDirector_Parser();
    virtual Caff parseCaff(std::string const filename);
    virtual ~SwigDirector_Parser();

    typedef void * (SWIGSTDCALL* SWIG_Callback0_t)(char *);
    void swig_connect_director(SWIG_Callback0_t callbackparseCaff);

private:
    SWIG_Callback0_t swig_callbackparseCaff;
    void swig_init_callbacks();
};

class SwigDirector_Caff : public Caff, public Swig::Director {

public:
    SwigDirector_Caff(std::shared_ptr< CaffNative > caff);
    virtual ~SwigDirector_Caff();
    virtual unsigned __int64 getAnimationNumber();
    virtual unsigned __int16 getYear();
    virtual unsigned __int8 getMonth();
    virtual unsigned __int8 getDay();
    virtual unsigned __int8 getHour();
    virtual unsigned __int8 getMinute();
    virtual std::vector< char > getCreator();
    virtual Caff::Ciff getCaffAnimation(unsigned int const ix);

    typedef unsigned long long (SWIGSTDCALL* SWIG_Callback0_t)();
    typedef unsigned short (SWIGSTDCALL* SWIG_Callback1_t)();
    typedef unsigned char (SWIGSTDCALL* SWIG_Callback2_t)();
    typedef unsigned char (SWIGSTDCALL* SWIG_Callback3_t)();
    typedef unsigned char (SWIGSTDCALL* SWIG_Callback4_t)();
    typedef unsigned char (SWIGSTDCALL* SWIG_Callback5_t)();
    typedef void * (SWIGSTDCALL* SWIG_Callback6_t)();
    typedef void * (SWIGSTDCALL* SWIG_Callback7_t)(unsigned int);
    void swig_connect_director(SWIG_Callback0_t callbackgetAnimationNumber, SWIG_Callback1_t callbackgetYear, SWIG_Callback2_t callbackgetMonth, SWIG_Callback3_t callbackgetDay, SWIG_Callback4_t callbackgetHour, SWIG_Callback5_t callbackgetMinute, SWIG_Callback6_t callbackgetCreator, SWIG_Callback7_t callbackgetCaffAnimation);

private:
    SWIG_Callback0_t swig_callbackgetAnimationNumber;
    SWIG_Callback1_t swig_callbackgetYear;
    SWIG_Callback2_t swig_callbackgetMonth;
    SWIG_Callback3_t swig_callbackgetDay;
    SWIG_Callback4_t swig_callbackgetHour;
    SWIG_Callback5_t swig_callbackgetMinute;
    SWIG_Callback6_t swig_callbackgetCreator;
    SWIG_Callback7_t swig_callbackgetCaffAnimation;
    void swig_init_callbacks();
};


#endif
