//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Parser : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Parser(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Parser obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Parser() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          caff_parser_wrapperPINVOKE.delete_Parser(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public void parseCaff(SWIGTYPE_p_std__string filename) {
    caff_parser_wrapperPINVOKE.Parser_parseCaff(swigCPtr, SWIGTYPE_p_std__string.getCPtr(filename));
    if (caff_parser_wrapperPINVOKE.SWIGPendingException.Pending) throw caff_parser_wrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_Caff getCaff() {
    SWIGTYPE_p_Caff ret = new SWIGTYPE_p_Caff(caff_parser_wrapperPINVOKE.Parser_getCaff(swigCPtr), true);
    return ret;
  }

  public Parser() : this(caff_parser_wrapperPINVOKE.new_Parser(), true) {
  }

}
